version: "3"

services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
  kafka1:
    image: abesalomi/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 19092:19092
    environment: 
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_CLUSTER://kafka1:19092,LISTENER_CLIENT://localhost:9092
      - KAFKA_LISTENERS=LISTENER_CLUSTER://kafka1:19092,LISTENER_CLIENT://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_CLUSTER:PLAINTEXT,LISTENER_CLIENT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_CLUSTER
  kafka2:
    image: abesalomi/kafka
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
      - 19093:19093
    environment: 
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_CLUSTER://kafka2:19093,LISTENER_CLIENT://localhost:9093
      - KAFKA_LISTENERS=LISTENER_CLUSTER://kafka2:19093,LISTENER_CLIENT://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_CLUSTER:PLAINTEXT,LISTENER_CLIENT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_CLUSTER