version: "3"

services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
  kafka:
    image: abesalomi/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 19092:19092